-- =====================================================
-- Q10c: Revenue by Device
-- Objective: Compare total revenue generated by device type
-- =====================================================

SELECT
    ws.device_type,
    ROUND(SUM(oi.price_usd), 2) AS total_revenue
FROM website_sessions ws
JOIN orders o
    ON ws.website_session_id = o.website_session_id
JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY ws.device_type;
