-- =====================================================
-- Q4a: Total Revenue
-- Objective: Calculate overall revenue generated by the business
-- =====================================================

SELECT
    ROUND(SUM(price_usd), 2) AS total_revenue
FROM order_items;
