-- =====================================================
-- Q10b: Orders by Device
-- Objective: Compare total orders generated by device type
-- =====================================================

SELECT
    ws.device_type,
    COUNT(DISTINCT o.order_id) AS total_orders
FROM website_sessions ws
JOIN orders o
    ON ws.website_session_id = o.website_session_id
GROUP BY ws.device_type;
