-- =====================================================
-- Q7c: Revenue by Channel (UTM Source)
-- Objective: Measure total revenue generated by each marketing channel
-- =====================================================

SELECT
    ws.utm_source,
    ROUND(SUM(oi.price_usd), 2) AS total_revenue
FROM website_sessions ws
JOIN orders o
    ON ws.website_session_id = o.website_session_id
JOIN order_items oi
    ON o.order_id = oi.order_id
WHERE ws.utm_source IS NOT NULL
GROUP BY ws.utm_source
ORDER BY total_revenue DESC;
